default:
 betaFileName: "./inst/extdata/methylation_example_short.csv"
 MultiModProbesFileName: "./inst/extdata/MultiModalCpG_short.csv"
 traitFileName: "./inst/extdata/traits_short.csv"
 sexFileName: "./inst/extdata/sex_short.csv" #file with gender information
 dataDir: "./inst/extdata/traitdata/"
 EWAScatalogFileName: "http://ewascatalog.org/static//docs/ewascatalog-results.txt.gz"
 baseURL_EWASDataHub: "https://bigd.big.ac.cn/ewas/datahub/probe/"
 baseURL_MRCEWASCatalog: "http://ewascatalog.org/?query="
 probeAttribut: "probeID"
 mergeAttribut: "ID_Kind"
 sexAttribut: "sex"
 sexFemaleValue: "w"
 sexMaleValue: "m"
 debugMode: FALSE
 debugModeLocalInst: FALSE